// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6hLQF2MVOy11ehQzhm4fme-sTe-U73U',
    appId: '1:675085278737:web:72c9dcc532bdb60280dbb0',
    messagingSenderId: '675085278737',
    projectId: 'chatwave-5846a',
    authDomain: 'chatwave-5846a.firebaseapp.com',
    storageBucket: 'chatwave-5846a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPcg2DEs3wys_A5At7O8KeDQghNm6ZQUw',
    appId: '1:675085278737:android:ec96d8ba59b121d380dbb0',
    messagingSenderId: '675085278737',
    projectId: 'chatwave-5846a',
    storageBucket: 'chatwave-5846a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-jdDg4DGBZEfSc83HusW9tOjWi61NfY',
    appId: '1:675085278737:ios:66c950f4ddfd673e80dbb0',
    messagingSenderId: '675085278737',
    projectId: 'chatwave-5846a',
    storageBucket: 'chatwave-5846a.appspot.com',
    iosBundleId: 'com.example.chatwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA-jdDg4DGBZEfSc83HusW9tOjWi61NfY',
    appId: '1:675085278737:ios:66c950f4ddfd673e80dbb0',
    messagingSenderId: '675085278737',
    projectId: 'chatwave-5846a',
    storageBucket: 'chatwave-5846a.appspot.com',
    iosBundleId: 'com.example.chatwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn6hLQF2MVOy11ehQzhm4fme-sTe-U73U',
    appId: '1:675085278737:web:f996da26a14f1fd980dbb0',
    messagingSenderId: '675085278737',
    projectId: 'chatwave-5846a',
    authDomain: 'chatwave-5846a.firebaseapp.com',
    storageBucket: 'chatwave-5846a.appspot.com',
  );
}
